[package]
name = "csvdb-python"
version.workspace = true
edition = "2021"

[lib]
name = "csvdb_python"
crate-type = ["cdylib"]

[dependencies]
csvdb = { path = "../csvdb" }
pyo3 = { version = "0.25", features = ["extension-module", "abi3-py38"] }
arrow = { version = "56", default-features = false, features = ["pyarrow"] }
anyhow = "1"
